spring:
  datasource:
    url: jdbc:mysql://192.168.2.10:3306/yblog_user?characterEncoding=UTF8
    username: root
    password: root
dubbo:
  registry:
    address: nacos://192.168.2.10:8888?namespace=4238579d-355d-4a8f-907c-7da94b094dd4
    register-mode: instance
  application:
    name: user-api
    qos-enable: false
  protocol:
    name: tri
    port: -1