server:
  port: 8082

spring:
  cloud:
    nacos:
      server-addr: localhost:8888
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/article/**
        - id: third-party
          uri: lb://third-party-service
          predicates:
            - Path=/email/**
  application:
    name: yblog-gateway