spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yblog_user?characterEncoding=UTF8
    username: root
    password: root

dubbo:
  registry:
    address: nacos://localhost:8888?namespace=4238579d-355d-4a8f-907c-7da94b094dd4
    register-mode: instance
  protocol:
    name: tri
    port: -1
