name: common-build
on:
  push:
    branches: master
jobs:
  build:
    name: maven-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up with jdk17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: test with maven
        run: mvn test
      - name: build with maven
        run: mvn build



